### ISSUE TITLE
jaxb2 plugin fails to generate class for simpleType  with xs:string restriction if enum value starts with numeric value

### ISSUE THREAD

**Issue by dfcoffin** [mojohaus/jaxb2-maven-plugin#102]
I am attempting to generate an enumeration class using jaxb2-maven-plugin from the ISO 19115 standard MD_CharacterSetCode definition.  The following is an excerpt from the full .xsd file:

[MD_CharacterSetCode.txt](https://github.com/mojohaus/jaxb2-maven-plugin/files/1697292/MD_CharacterSetCode.txt)

The Jaxb2 plugin generates the MDCharacterSetCode enumeration class as long as none of the "8859partn" enumeration values are processed.  When they are not commented out, no enumeration class is generated, and the Jaxb2 plugin reports BUILD Successful.

If there is anything else I can provide, please let me know.

**Comment by dfcoffin** [comment]
Is there a projected date for the 2.4 Release?

**Comment by lennartj** [comment]
This is an issue with the underlying tool, XJC, and not with the jaxb2-maven-plugin.
If you run the command manually (i.e. XJC directly) you will see no XJC output when the inbound enum contains values which start with digits.

... and since the jaxb2-maven-plugin only delegates to the underlying JDK tools, this is not something which can be solved by us.

**Comment by dfcoffin** [comment]
@lennartj 

Who maintains the JDK tools?  I'll post the problem to their site.

**Comment by lennartj** [comment]
The JDK development takes place at openjdk.java.net.

It seems that their bug tracker is found at https://bugs.openjdk.java.net/secure/Dashboard.jspa
