### ISSUE TITLE
Build fails if module path to child project is not linear

### ISSUE THREAD

**Issue by pieter-v** [mojohaus/jaxb2-maven-plugin#53]
If the directory name of the child pom (with jaxb2-maven-plugin) starts with directory name of the parent pom, then the build fails if initiated from the parent pom, but the build succeeds if initiated from the child pom.

Attached sample project that illustrates the problem

to reproduce:

cd project-a
mvn clean install (=> success)
cd ../project
mvn clean install (=> fail)
[jaxb2-dir-issue.zip](https://github.com/mojohaus/jaxb2-maven-plugin/files/426710/jaxb2-dir-issue.zip)

**Comment by lennartj** [comment]
This is not the case.

If you actually create a project where a child module starts with the same name as the parent project, all works fine. The issue here is that your parent pom (in the attached ZIP) resides at the path ../project, implying that the paths are calculated incorrectly.

Therefore, the problem description and the attached ZIP describe 2 different problems.

**Comment by lennartj** [comment]
Moving this issue and discussion to #131
