### ISSUE TITLE
 ObjectFactory not marked as @Generated with -mark-generated

### ISSUE THREAD

**Issue by NargiT** [mojohaus/jaxb2-maven-plugin#6]
Hello,

When we add <arguments>-mark-generated</arguments> in the plugins (v 1.6) all classes are marked @Generated except ObjectFactory and package-info.java.

Is it a bug ? Or there is a special way to add it ?

This actually breaking build if used with checkstyle plugin.

Tigran

**Comment by NargiT** [comment]
package-info.java also has the same issue

**Comment by lennartj** [comment]
At the moment, we do not have an IT for this.
I'll create one so we can track this issue.

**Comment by lennartj** [comment]
It would appear that this behavior is the standard one for XJC.

While I strive for the Jaxb2-Maven-Plugin to simplify the usage of XJC (and SchemaGen too, of course), I am not certain it is a good idea to alter the standard behavior. I agree, though, that this seems  problematic. However, I think that this issue should be logged with the XJC development team rather than with this plugin (and I also think that this issue is very valid) so that this enhancement is implemented at the correct place. 

Would you please log an issue with the XJC team instead?

**Comment by lennartj** [comment]
IT added in e95d64c

**Comment by NargiT** [comment]
Yeap I did that https://github.com/gf-metro/jaxb/issues/16.

But it will require for to upgrade the version of xjc in your pluging right ?
