### ISSUE TITLE
Execution of plugin in subartifact differs from windows to unix

### ISSUE THREAD

**Issue by StrawBerryAtWork** [mojohaus/jaxb2-maven-plugin#8]
Hello,

I'm using the jaxb2-maven-plugin and its goal xjc to generate Java classes from xsd.

I'm using Maven 3.0.4, but I made also some tests in Maven 3.0.5 and 3.2.5, running in java 1.6 and get the same error. 

The plugin is using relative path in unix while he doesn't in windows.

So, when I use the plugin in a subartifact of my main artifact, in windows, I get my classes generated but in Unix I get a FileNotFoundException.

I have uploaded a mini project for tests : https://github.com/StrawBerryAtWork/jaxb2-maven-plugin

You can also find unix and windows logs.

Finally, the problem doesn't seem to exist in version 1.6 of the plugin.

Straw

**Comment by Batmat** [comment]
Hi,

IIUC, I've encountered that issue recently and already fixed it locally.
I'll file a PR asap for review.
I didn't do it yet because I wanted to write an IT to do it correctly in
the public sources.

Would be absolutely great if you could provide a basic test case (say a
little multimodule project showing the issue).

Thanks

2015-06-29 16:39 GMT+02:00 Straw Berry <notifications@github.com>:

> Hello,
>
> I'm using the jaxb2-maven-plugin and its goal xjc to generate Java classes
> from xsd.
>
> I'm using Maven 3.0.4, but I made also some tests in Maven 3.0.5 and
> 3.2.5, running in java 1.6 and get the same error.
>
> The plugin is using relative path in unix while he doesn't in windows.
>
> So, when I use the plugin in a subartifact of my main artifact, in
> windows, I get my classes generated but in Unix I get a
> FileNotFoundException.
>
> Straw
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/jaxb2-maven-plugin/issues/8>.
>



-- 
Baptiste <Batmat> MATHUS - http://batmat.net
Sauvez un arbre,
Mangez un castor !

**Comment by StrawBerryAtWork** [comment]
Hi Batmat,

I updated my issue with a link to a mini project with tests : https://github.com/StrawBerryAtWork/jaxb2-maven-plugin

Let me know if you have access to the files.

Straw

**Comment by isartcanyameres** [comment]
Hi all, 
I've the same issue in unix, where xjc doesn't seem to get the correct path for its sources when subartifacts are involved.
I'll use Straw sample to explain my findings.

In provided unix log one can see that the resource filer resolves the xsd correctly, see [line 688](https://github.com/StrawBerryAtWork/jaxb2-maven-plugin/blob/master/jaxb2-unix-debug.log#L688).

However, when it is translated into XJC arguments, only the path relative to the subartifact is passed, as shown in [line 709](https://github.com/StrawBerryAtWork/jaxb2-maven-plugin/blob/master/jaxb2-unix-debug.log#L709)

In case XJC is invoked from a different location, which is currently happening when building from the parent artifact, XJC wouldn't be able to find the file, as given path is not relative to its location.
This is exactly what is happening in [line 766](https://github.com/StrawBerryAtWork/jaxb2-maven-plugin/blob/master/jaxb2-unix-debug.log#L766) (if I understood it correctly :P)

**Comment by lennartj** [comment]
Fixed an IT to close this issue, by simply using the absolute path of each source.
This may cause problems due to long paths in some corner cases, but should ensure that submodule projects can work properly.

It works on Mac and Linux at the moment. Could you folks please pull/clone and build on Windows as well?

**Comment by lennartj** [comment]
I'll close this issue for now; in case we find this is still an issue, we can reopen this issue.

**Comment by batmat** [comment]
@isartcanyameres Out of curiosity, did you have a chance to test the last version, and see if it fixes that issue? Thanks
